//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Measurement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string P_number { get; set; }
        public string T_size { get; set; }
        public string P_size { get; set; }
        public string UserType { get; set; }
    }
}
